buy_indicator_config = {"K": {"range": [0, 20], "name": "KDJ的K值在范围[0,20]",
                              "other_show_indicator": ['D', 'ADX', 'plus_di', 'minus_di']},
                        "pre_K": {"range": [0, 20], "name": "pre_KDJ的K值在范围[0,20]",
                                  "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di']},
                        "自定义20日均线": {"gt": "close", "name": "20日均线大于收盘价",
                                           "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di']},
                        "D": {"range": [0, 20], "name": "KDJ的D值在范围[0,20]",
                              "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di']},
                        "pre_D": {"range": [0, 20], "name": "prd_KDJ的D值在范围[0,20]",
                                  "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di']},
                        "rsi12": {"range": [0, 20], "name": "rsi12值在范围[0,20]",
                                  "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di']},
                        "obv120_cross": {"eq": 1, "name": "能量潮信号",
                                         "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di',
                                                                  'slow_obv_diff', 'rsi12']},
                        "obv20_cross": {"eq": 1, "name": "能量潮信号",
                                        "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di',
                                                                 'slow_obv_diff', 'rsi12']},
                        "up": {"gt": 1, "name": "大于2个峰点",
                               "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di',
                                                        'slow_obv_diff', 'rsi12']},
                        }

sell_indicator_config = {"K": {"range": [70, 100], "name": "KDJ的K值在范围[70, 100]",
                               "other_show_indicator": ['D', 'ADX', 'plus_di', 'minus_di']},
                         "pre_K": {"range": [70, 100], "name": "pre_KDJ的K值在范围[70, 100]",
                                   "other_show_indicator": ['D', 'ADX', 'plus_di', 'minus_di']},
                         "D": {"range": [70, 100], "name": "KDJ的D值在范围[70, 100]",
                               "other_show_indicator": ['D', 'ADX', 'plus_di', 'minus_di']},
                         "pre_D": {"range": [70, 100], "name": "pre_KDJ的D值在范围[70, 100]",
                                   "other_show_indicator": ['D', 'ADX', 'plus_di', 'minus_di']},
                         "rsi12": {"range": [70, 100], "name": "rsi12值在范围[70,100]",
                                   "other_show_indicator": ['D', 'ADX', 'plus_di', 'minus_di']},
                         "dead_obv120_cross": {"eq": 1, "name": "能量潮信号",
                                               "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di',
                                                                        'slow_obv_diff', 'rsi12']},
                         "dead_obv20_cross": {"eq": 1, "name": "能量潮信号",
                                              "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di',
                                                                       'slow_obv_diff', 'rsi12']},
                         "down": {"gt": 3, "name": "小于3个峰点",
                                  "other_show_indicator": ['D', 'K', 'ADX', 'plus_di', 'minus_di',
                                                           'slow_obv_diff', 'rsi12']}
                         }
